### PR TITLE
PHP 8.0 support

### LINKED ISSUE #8: PHP 8.0 support
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

To be prepared for the december release of PHP 8.0, this repository has some additional TODOs to be tested against the new major version.

In order to make this repository compatible, one has to follow these steps:

- [ ] Modify `composer.json` to provide support for PHP 8.0 by adding the constraint `~8.0.0`
- [ ] Modify `composer.json` to drop support for PHP less than 7.3
- [ ] Modify `composer.json` to implement phpunit 9.3 which supports PHP 7.3+
- [ ] Modify `.travis.yml` to ignore platform requirements when installing composer dependencies (simply add `--ignore-platform-reqs` to `COMPOSER_ARGS` env variable)
- [ ] Modify `.travis.yml` to add PHP 8.0 to the matrix (*NOTE*: Do not allow failures as PHP 8.0 has a feature freeze since 2020-08-04!)
- [ ] Modify source code in case there are incompatibilities with PHP 8.0

### PR DESCRIPTION
**Pull request by Thaix**
Signed-off-by: Oliver Peters <oliver_pet@web.de>

|    Q          |   A
|-------------- | ------
| New Feature   | yes

### Description
drop support for PHP versions < 7.3
add support for PHP 8.0
update PhpUnit to 9.4.1

### CODE REVIEW

**Comment by Xerkus** [comment]
@Thaix congratulations on the start of your Open Source contributions track on GitHub and thank you!

I would like to give you a best practices advice for Git/GitHub: Try to avoid using main branches to introduce changes and create topic branches instead. Working from topic branches allows to isolate development work without affecting other branches in the repository and to work on multiple topics and their pull requests simultaneously.

Here is a short example using cli. I am assuming git `remote` pointing to this repository is called `upstream` and your fork is `origin` (you can check it with `git remote -v`).

Create topic branch:
```bash
git fetch upstream
git checkout -b feature/upgrade-to-php8 upstream/1.3.x
```

Commit changes to topic branch and push to your fork:
```bash
git push origin feature/upgrade-to-php8
```

Now you are ready to open pull request from the topic branch in your fork.
It is possible to add more changes to the opened pull request by committing more changes to the topic branch and pushing it to your fork. Open pull request is automatically updated when its linked branch is updated.

**Comment by Thaix** [comment]
@Xerkus Thank you very much for the detailed explanation. In my first 2 PR I created a featurebranch already. Seems like i forgot it this time.
upstream is new to me, i will have a look at it. My workflow was like: fork repo, create a new branch, fetch it from origin, push to orgin, open PR to original repo.

Is there any action needed on my side, or was it just an advice.

**Comment by Xerkus** [comment]
@Thaix just an advice, no action needed.

You need to have a remote for this repository to fetch updates. Naming it `upstream` is a common convention, which you can see if you use new official github cli command `gh`:

```
$ gh repo clone laminas/laminas-psr7bridge
  Cloning into 'laminas-psr7bridge'...
  ...
$ cd laminas-psr7bridge
$ git remote -v
  origin	https://github.com/laminas/laminas-psr7bridge.git (fetch)
  origin	https://github.com/laminas/laminas-psr7bridge.git (push)
$ gh repo fork
  - Forking laminas/laminas-psr7bridge...
  ! Xerkus/laminas-psr7bridge already exists
  ? Would you like to add a remote for the fork? Yes
  ✓ Renamed origin remote to upstream
  ✓ Added remote origin
$ git remote -v
  origin	https://github.com/Xerkus/laminas-psr7bridge.git (fetch)
  origin	https://github.com/Xerkus/laminas-psr7bridge.git (push)
  upstream	https://github.com/laminas/laminas-psr7bridge.git (fetch)
  upstream	https://github.com/laminas/laminas-psr7bridge.git (push)
```

If you like you can join our community [Slack chat](https://laminas.dev/chat/#slack), we are always happy to provide help and guidance.

**Review by Ocramius — APPROVED** [review]

**Comment by Ocramius** [comment]
Merging as-is, since git history is clean.

**Comment by Ocramius** [comment]
Thanks @Thaix!

**Pull request merged**
